osx_image: xcode7
before_install:
  - brew update; brew update # Workaround for https://github.com/Homebrew/homebrew/issues/42553
  - brew outdated xctool || brew upgrade xctool
language: objective-c
xcode_project: ZipUtilities.xcodeproj
matrix:
  include:
    - xcode_scheme: ZipUtilities
      xcode_sdk: iphonesimulator
    - xcode_scheme: ZipUtilities Framework
      xcode_sdk: iphonesimulator
    - xcode_scheme: ZipUtilities OSX Framework
